package hospital.coreservice.model.enums;

public enum Speciality {
    CARDIOLOGY,
    INTERNAL_MEDICINE,
    PEDIATRICS,
    NEUROLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    NEPHROLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    INFECTIOUS_DISEASES,
    GENERAL_SURGERY,
    CARDIAC_SURGERY,
    NEUROSURGERY,
    ORTHOPEDICS,
    PLASTIC_SURGERY,
    RADIOLOGY,
    PATHOLOGY,
    ANESTHESIOLOGY,
    EMERGENCY_MEDICINE,
    FAMILY_MEDICINE,
    PSYCHIATRY
}
