package hospital.adminservice.repository;

import hospital.adminservice.model.Report;
import hospital.adminservice.model.enums.ReportStatus;
import hospital.adminservice.model.enums.ReportType;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Repository for Report entity.
 *
 * <p><strong>Custom Queries:</strong></p>
 * <ul>
 *   <li>findByType - Reports by type</li>
 *   <li>findByStatus - Reports by status</li>
 *   <li>findByGeneratedBy - Reports by user</li>
 *   <li>findPendingReports - Pending reports</li>
 *   <li>findProcessingReports - Currently processing</li>
 *   <li>findCompletedReports - Successfully completed</li>
 *   <li>findFailedReports - Failed reports</li>
 *   <li>findExpiredReports - Expired reports for cleanup</li>
 * </ul>
 *
 * @author MobinaRahi
 */
@Repository
public interface ReportRepository extends BaseEntityRepository<Report, Long> {

    /**
     * Finds reports by type.
     *
     * @param type the report type
     * @return list of reports with the type
     */
    List<Report> findByType(ReportType type);

    /**
     * Finds reports by status.
     *
     * @param status the report status
     * @return list of reports with the status
     */
    List<Report> findByStatus(ReportStatus status);

    /**
     * Finds reports generated by a specific user.
     *
     * @param generatedBy the user ID
     * @return list of reports generated by the user
     */
    List<Report> findByGeneratedBy(Long generatedBy);

    /**
     * Finds reports generated in a date range.
     *
     * @param startDate start date
     * @param endDate   end date
     * @return list of reports in range
     */
    @Query("SELECT r FROM Report r WHERE r.generatedAt BETWEEN :startDate AND :endDate AND r.deleted = false")
    List<Report> findByGeneratedAtBetween(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);

    /**
     * Finds all pending reports.
     *
     * @return list of pending reports
     */
    List<Report> findByStatusOrderByGeneratedAtAsc(ReportStatus status);

    /**
     * Finds expired reports for cleanup.
     *
     * @param beforeDate reports expired before this date
     * @return list of expired reports
     */
    @Query("SELECT r FROM Report r WHERE r.status = 'EXPIRED' AND r.updatedAt < :beforeDate AND r.deleted = false")
    List<Report> findExpiredReportsBefore(@Param("beforeDate") LocalDateTime beforeDate);

    /**
     * Counts reports by type and status.
     *
     * @param type   the report type
     * @param status the report status
     * @return report count
     */
    @Query("SELECT COUNT(r) FROM Report r WHERE r.type = :type AND r.status = :status AND r.deleted = false")
    long countByTypeAndStatus(@Param("type") ReportType type, @Param("status") ReportStatus status);

    /**
     * Finds latest report of a specific type.
     *
     * @param type the report type
     * @return latest report if found
     */
    @Query("SELECT r FROM Report r WHERE r.type = :type AND r.deleted = false ORDER BY r.generatedAt DESC")
    List<Report> findLatestByType(@Param("type") ReportType type);
}
