package hospital.coreservice.mapper;

import hospital.coreservice.dto.appointment.AppointmentCreateDto;
import hospital.coreservice.dto.appointment.AppointmentResponseDto;
import hospital.coreservice.dto.appointment.AppointmentUpdateDto;
import hospital.coreservice.model.Appointment;
import org.mapstruct.*;

/**
 * Mapper for Appointment entity.
 * <p>
 * Converts between Appointment Entity and various DTOs (Create, Update, Response).
 * Relationships (patient, doctor, department) are ignored during creation/update
 * because they are represented as IDs (Long) in DTOs and require manual fetching
 * from database in the Service layer.
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {PatientMapper.class, DoctorMapper.class, DepartmentMapper.class}
)
public interface AppointmentMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new appointment.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>patient, doctor, department - are IDs in DTO (Long), need manual fetch in Service</li>
     *   <li>createdAt, createdBy - populated automatically by system</li>
     *   <li>canceledBy, canceledReason, canceledAt - only set when appointment is cancelled</li>
     *   <li>deleted - default value is false</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Appointment entity (without relationships)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "patient", ignore = true)
    @Mapping(target = "doctor", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "canceledBy", ignore = true)
    @Mapping(target = "canceledReason", ignore = true)
    @Mapping(target = "canceledAt", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    Appointment toEntity(AppointmentCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated (partial update support).
     * Relationships are ignored because they require separate endpoints
     * (e.g., reassign appointment to another patient).
     * </p>
     *
     * @param appointment the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "patient", ignore = true)
    @Mapping(target = "doctor", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "canceledAt", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    void updateEntity(@MappingTarget Appointment appointment, AppointmentUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     * <p>
     * Uses PatientMapper, DoctorMapper, and DepartmentMapper (declared in @Mapper.uses)
     * to automatically convert nested entities to their respective DTOs.
     * The @Mappings are explicitly declared for clarity, even though they are optional
     * when source and target field names match.
     * </p>
     *
     * @param appointment the entity to convert
     * @return complete DTO for client response (includes full nested objects)
     */
    AppointmentResponseDto toResponseDto(Appointment appointment);
}