package hospital.coreservice.mapper;

import com.hospital.coreService.dto.department.DepartmentCreateDto;
import com.hospital.coreService.dto.department.DepartmentResponseDto;
import com.hospital.coreService.dto.department.DepartmentUpdateDto;
import com.hospital.coreService.model.Department;
import org.mapstruct.*;

/**
 * Mapper for Department entity.
 * <p>
 * Converts between Department Entity and various DTOs (Create, Update, Response).
 * Relationships (headDoctor, headNurse, lists) are ignored during creation/update
 * and are handled manually in the Service layer.
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {DoctorMapper.class, NurseMapper.class}
)
public interface DepartmentMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>headDoctor, headNurse - are IDs in DTO (Long), need manual fetch in Service</li>
     *   <li>doctorList, nurseList, roomList - empty by default</li>
     *   <li>isActive - default value true in Entity</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Department entity (without relationships)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "headDoctor", ignore = true)
    @Mapping(target = "headNurse", ignore = true)
    @Mapping(target = "doctorList", ignore = true)
    @Mapping(target = "nurseList", ignore = true)
    @Mapping(target = "roomList", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    Department toEntity(DepartmentCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing Entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated.
     * Relationships are ignored because they require separate endpoints.
     * </p>
     *
     * @param department the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "headDoctor", ignore = true)
    @Mapping(target = "headNurse", ignore = true)
    @Mapping(target = "doctorList", ignore = true)
    @Mapping(target = "nurseList", ignore =true)
    @Mapping(target = "roomList", ignore = true)
    void updateEntity(@MappingTarget Department department, DepartmentUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto.
     * <p>
     * Uses DoctorMapper and NurseMapper (declared in @Mapper.uses)
     * to automatically convert headDoctor and headNurse to their DTOs.
     * Lists are also mapped automatically using the same mappers.
     * </p>
     *
     * @param department the entity to convert
     * @return complete DTO for client response
     */
    DepartmentResponseDto toResponseDto(Department department);
}