package hospital.coreservice.mapper;

import hospital.coreservice.dto.doctor.DoctorCreateDto;
import hospital.coreservice.dto.doctor.DoctorResponseDto;
import hospital.coreservice.dto.doctor.DoctorUpdateDto;
import hospital.coreservice.model.Doctor;
import org.mapstruct.*;

/**
 * Mapper for Doctor entity.
 * <p>
 * Converts between Doctor Entity and various DTOs (Create, Update, Response).
 * Relationships (department, doctorSchedules) are ignored during creation/update
 * because they are represented as IDs (Long) in DTOs and require manual fetching
 * from database in the Service layer.
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {DepartmentMapper.class,DoctorScheduleMapper.class}
)
public interface DoctorMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new doctor.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>doctorSchedules - added separately after doctor is created</li>
     *   <li>department - is ID in DTO (Long), need manual fetch in Service</li>
     *   <li>isActive - default value is true</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Doctor entity (without relationships)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "doctorSchedules", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    Doctor toEntity(DoctorCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated (partial update support).
     * Relationships are ignored because they require separate endpoints.
     * </p>
     *
     * @param doctor the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "doctorSchedules", ignore = true)
    @Mapping(target = "department", ignore = true)
    void updateEntity(@MappingTarget Doctor doctor, DoctorUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     * <p>
     * Uses DepartmentMapper (declared in @Mapper.uses) to automatically convert
     * department to DepartmentResponseDto.
     * </p>
     *
     * @param doctor the entity to convert
     * @return complete DTO for client response
     */
    DoctorResponseDto toResponseDto(Doctor doctor);
}