package hospital.coreservice.mapper;

import com.hospital.coreService.dto.doctor_schedule.DoctorScheduleCreateDto;
import com.hospital.coreService.dto.doctor_schedule.DoctorScheduleResponseDto;
import com.hospital.coreService.dto.doctor_schedule.DoctorScheduleUpdateDto;
import com.hospital.coreService.model.DoctorSchedule;
import org.mapstruct.*;

/**
 * Mapper for DoctorSchedule entity.
 * <p>
 * Converts between DoctorSchedule Entity and various DTOs (Create, Update, Response).
 * The doctor relationship is ignored during creation/update because it is represented
 * as doctorId (Long) in DTOs and requires manual fetching in the Service layer.
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {DoctorMapper.class}
)
public interface DoctorScheduleMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new doctor schedule.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>doctor - is ID (doctorId) in DTO, need manual fetch in Service</li>
     *   <li>isActive - default value is true</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new DoctorSchedule entity (without doctor relationship)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "doctor", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    DoctorSchedule toEntity(DoctorScheduleCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated (partial update support).
     * </p>
     *
     * @param doctorSchedule the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "doctor", ignore = true)
    void updateEntity(@MappingTarget DoctorSchedule doctorSchedule, DoctorScheduleUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     * <p>
     * The doctor field will be mapped automatically if DoctorMapper is available.
     * If you need full doctor details in response, add uses = {DoctorMapper.class}
     * to @Mapper annotation.
     * </p>
     *
     * @param doctorSchedule the entity to convert
     * @return DTO for client response
     */
    DoctorScheduleResponseDto toResponseDto(DoctorSchedule doctorSchedule);
}