package hospital.coreservice.mapper;

import hospital.coreservice.dto.nurse.NurseCreateDto;
import hospital.coreservice.dto.nurse.NurseResponseDto;
import hospital.coreservice.dto.nurse.NurseUpdateDto;
import hospital.coreservice.model.Nurse;
import org.mapstruct.*;

/**
 * Mapper for Nurse entity.
 * <p>
 * Converts between Nurse Entity and various DTOs (Create, Update, Response).
 * Relationships (departmentList, shiftPreferenceList) are ignored during creation/update
 * because they are represented as Lists of IDs in DTOs and require manual fetching
 * from database in the Service layer (Many-to-Many relationships).
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {DepartmentMapper.class, ShiftMapper.class}
)
public interface NurseMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new nurse.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>departmentList - is List of IDs in DTO, need manual fetch in Service</li>
     *   <li>shiftPreferenceList - is List of IDs in DTO, need manual fetch in Service</li>
     *   <li>isActive - default value is true</li>
     *   <li>createdAt - populated automatically by system</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Nurse entity (without relationships)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "departmentList", ignore = true)
    @Mapping(target = "shiftPreferenceList", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    Nurse toEntity(NurseCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated (partial update support).
     * Relationships are ignored because they require separate endpoints
     * for adding/removing departments and shifts.
     * </p>
     *
     * @param nurse the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "departmentList", ignore = true)
    @Mapping(target = "shiftPreferenceList", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    void updateEntity(@MappingTarget Nurse nurse, NurseUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     * <p>
     * Uses DepartmentMapper and ShiftMapper (declared in @Mapper.uses)
     * to automatically convert departmentList and shiftPreferenceList to their DTOs.
     * </p>
     *
     * @param nurse the entity to convert
     * @return complete DTO for client response
     */
    NurseResponseDto toResponseDto(Nurse nurse);
}
