package hospital.coreservice.mapper;

import com.hospital.coreService.dto.patient.PatientCreateDto;
import com.hospital.coreService.dto.patient.PatientResponseDto;
import com.hospital.coreService.dto.patient.PatientUpdateDto;
import com.hospital.coreService.model.Patient;
import org.mapstruct.*;

/**
 * Mapper for Patient entity.
 * <p>
 * Converts between Patient Entity and various DTOs (Create, Update, Response).
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface PatientMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new patient.
     * <p>
     * Fields ignored because they are auto-generated or system-managed:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>createdAt, updatedAt - populated automatically</li>
     *   <li>deleted - default value is false</li>
     *   <li>currentRoom - is ID in DTO, needs manual fetch in Service</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Patient entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "currentRoom", ignore = true)
    Patient toEntity(PatientCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated.
     * </p>
     *
     * @param patient the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "currentRoom", ignore = true)
    void updateEntity(@MappingTarget Patient patient, PatientUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     * <p>
     * If you need currentRoom to be converted to RoomResponseDto,
     * add uses = {RoomMapper.class} to @Mapper annotation.
     * </p>
     *
     * @param patient the entity to convert
     * @return complete DTO for client response
     */
    PatientResponseDto toResponseDto(Patient patient);
}