package hospital.coreservice.mapper;

import hospital.coreservice.dto.room.RoomCreateDto;
import hospital.coreservice.dto.room.RoomResponseDto;
import hospital.coreservice.dto.room.RoomUpdateDto;
import hospital.coreservice.model.Room;
import org.mapstruct.*;

/**
 * Mapper for Room entity.
 * <p>
 * Converts between Room Entity and various DTOs (Create, Update, Response).
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        uses = {DepartmentMapper.class, PatientMapper.class}
)
public interface RoomMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new room.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>department - is ID in DTO, need manual fetch in Service</li>
     *   <li>currentPatientList - empty by default</li>
     *   <li>isOccupied - default value is false</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Room entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "currentPatientList", ignore = true)
    @Mapping(target = "isOccupied", ignore = true)
    Room toEntity(RoomCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated.
     * </p>
     *
     * @param room the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "currentPatientList", ignore = true)
    void updateEntity(@MappingTarget Room room, RoomUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     *
     * @param room the entity to convert
     * @return complete DTO for client response
     */
    RoomResponseDto toResponseDto(Room room);
}