package hospital.coreservice.mapper;

import com.hospital.coreService.dto.shift.ShiftCreateDto;
import com.hospital.coreService.dto.shift.ShiftResponseDto;
import com.hospital.coreService.dto.shift.ShiftUpdateDto;
import com.hospital.coreService.model.Shift;
import org.mapstruct.*;

/**
 * Mapper for Shift entity.
 * <p>
 * Converts between Shift Entity and various DTOs (Create, Update, Response).
 * </p>
 *
 * @author Mobina
 * @version 1.0
 * @since 1.0
 */
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface ShiftMapper {

    // ========== Create Mapping ==========

    /**
     * Converts CreateDto to Entity for saving a new shift.
     * <p>
     * Fields ignored because:
     * <ul>
     *   <li>id - auto-generated by database</li>
     *   <li>isActive - default value is true</li>
     * </ul>
     * </p>
     *
     * @param createDto the DTO containing creation data
     * @return new Shift entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    Shift toEntity(ShiftCreateDto createDto);

    // ========== Update Mapping ==========

    /**
     * Updates existing entity with values from UpdateDto.
     * <p>
     * Only non-null fields in DTO will be updated.
     * </p>
     *
     * @param shift the existing entity to update (modified in place)
     * @param updateDto the DTO containing updated values
     */
    @Mapping(target = "id", ignore = true)
    void updateEntity(@MappingTarget Shift shift, ShiftUpdateDto updateDto);

    // ========== Response Mapping ==========

    /**
     * Converts Entity to ResponseDto for sending back to client.
     *
     * @param shift the entity to convert
     * @return complete DTO for client response
     */
    ShiftResponseDto toResponseDto(Shift shift);
}