-- ============================================================
-- Oracle init script — creates application schemas
--
-- NOTE: gvenzl/oracle-xe runs init scripts against XEPDB1 (PDB)
-- automatically. Do NOT use ALTER SESSION SET CONTAINER here.
-- ============================================================

-- Create auth user
CREATE USER auth IDENTIFIED BY auth123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO auth;
ALTER USER auth QUOTA UNLIMITED ON USERS;

-- Create core user
CREATE USER core IDENTIFIED BY core123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO core;
ALTER USER core QUOTA UNLIMITED ON USERS;

-- Create clinical user
CREATE USER clinical IDENTIFIED BY clinical123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO clinical;
ALTER USER clinical QUOTA UNLIMITED ON USERS;

-- Create inventory user
CREATE USER inventory IDENTIFIED BY inventory123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO inventory;
ALTER USER inventory QUOTA UNLIMITED ON USERS;

-- Create admin user
CREATE USER admin IDENTIFIED BY admin123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO admin;
ALTER USER admin QUOTA UNLIMITED ON USERS;

-- Create billing user
CREATE USER billing IDENTIFIED BY billing123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO billing;
ALTER USER billing QUOTA UNLIMITED ON USERS;

-- Create lab user
CREATE USER lab IDENTIFIED BY lab123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO lab;
ALTER USER lab QUOTA UNLIMITED ON USERS;

-- Create notification user
CREATE USER notification IDENTIFIED BY notification123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
    CREATE PROCEDURE, CREATE TRIGGER TO notification;
ALTER USER notification QUOTA UNLIMITED ON USERS;