package hospital.adminservice.service;

import hospital.adminservice.dto.report.ReportCreateDto;
import hospital.adminservice.dto.report.ReportResponseDto;
import hospital.adminservice.model.enums.ReportStatus;
import hospital.adminservice.model.enums.ReportType;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Service interface for Report management.
 *
 * <p><strong>Business Rules:</strong></p>
 * <ul>
 *   <li>Reports can be generated on-demand or scheduled</li>
 *   <li>Each report has a type that determines its content</li>
 *   <li>Parameters are stored as JSON string for flexibility</li>
 *   <li>Generated files are stored with a URL reference</li>
 *   <li>Report status tracks the generation lifecycle</li>
 *   <li>Soft delete supported</li>
 * </ul>
 *
 * <p><strong>Status Workflow:</strong></p>
 * <pre>
 * PENDING → PROCESSING → COMPLETED
 *                       → FAILED
 * COMPLETED → EXPIRED (after retention period)
 * </pre>
 *
 * <p><strong>Report Types:</strong></p>
 * <ul>
 *   <li>PATIENT_STATS: Patient statistics and demographics</li>
 *   <li>APPOINTMENT_STATS: Appointment analytics</li>
 *   <li>FINANCIAL_DAILY/MONTHLY/YEARLY: Financial reports</li>
 *   <li>DOCTOR_PERFORMANCE: Doctor productivity metrics</li>
 *   <li>BED_OCCUPANCY: Bed utilization reports</li>
 *   <li>REVENUE_BY_INSURANCE/SERVICE: Revenue breakdowns</li>
 *   <li>COLLECTION_REPORT: Payment collection reports</li>
 *   <li>DELAYED_PAYMENTS: Outstanding payments report</li>
 * </ul>
 *
 * @author MobinaRahi
 */
public interface ReportService {

    /**
     * Creates a new report generation request.
     *
     * @param dto the report creation data
     * @return the created report
     */
    ReportResponseDto createReport(ReportCreateDto dto);

    /**
     * Gets a report by its ID.
     *
     * @param id the report ID
     * @return the report
     */
    ReportResponseDto getReportById(Long id);

    /**
     * Gets reports by type.
     *
     * @param type the report type
     * @return list of reports with the type
     */
    List<ReportResponseDto> getReportsByType(ReportType type);

    /**
     * Gets reports by status.
     *
     * @param status the report status
     * @return list of reports with the status
     */
    List<ReportResponseDto> getReportsByStatus(ReportStatus status);

    /**
     * Gets reports generated by a specific user.
     *
     * @param generatedBy the user ID
     * @return list of reports generated by the user
     */
    List<ReportResponseDto> getReportsByUser(Long generatedBy);

    /**
     * Gets reports generated in a date range.
     *
     * @param startDate start date
     * @param endDate   end date
     * @return list of reports in range
     */
    List<ReportResponseDto> getReportsByDateRange(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Gets pending reports ordered by generation time.
     *
     * @return list of pending reports
     */
    List<ReportResponseDto> getPendingReports();

    /**
     * Gets expired reports for cleanup.
     *
     * @param beforeDate reports expired before this date
     * @return list of expired reports
     */
    List<ReportResponseDto> getExpiredReports(LocalDateTime beforeDate);

    /**
     * Marks a report as being processed.
     *
     * @param id the report ID
     * @return the updated report
     */
    ReportResponseDto markAsProcessing(Long id);

    /**
     * Marks a report as successfully completed.
     *
     * @param id      the report ID
     * @param fileUrl the URL to the generated report file
     * @return the updated report
     */
    ReportResponseDto markAsCompleted(Long id, String fileUrl);

    /**
     * Marks a report generation as failed.
     *
     * @param id the report ID
     * @return the updated report
     */
    ReportResponseDto markAsFailed(Long id);

    /**
     * Soft-deletes a report.
     *
     * @param id the report ID
     */
    void deleteReport(Long id);

    /**
     * Counts reports by type and status.
     *
     * @param type   the report type
     * @param status the report status
     * @return report count
     */
    long countByTypeAndStatus(ReportType type, ReportStatus status);
}
